import { TOKENS } from "./tokens";
import { DFSState } from "./dfs"; // todo: add dfsstate to the transition table itself

/**
 * Transition table for the lexer. This is a 2D table that maps the current state and the input token to the next state.
 */
type TransitionTable = Record<TOKENS, Record<TOKENS, TOKENS>>;


/**
 * The actual transition table. This is a simple example and can be expanded to include more states and transitions as needed.
 */
// TODO: Refactor this transition table to a nested hashtable, from the DFS State you should get a hashtable based on the symbol, and based on that change the DFS State.
export const transitionTable: TransitionTable = {
  [TOKENS.IDENTIFIER]: {
    [TOKENS.IDENTIFIER]: TOKENS.IDENTIFIER,
    [TOKENS.NUMBER]: TOKENS.IDENTIFIER,
    [TOKENS.STRING]: TOKENS.IDENTIFIER,
    [TOKENS.OPERATOR]: TOKENS.IDENTIFIER,
    [TOKENS.KEYWORD]: TOKENS.IDENTIFIER,
    [TOKENS.PUNCTUATION]: TOKENS.IDENTIFIER,
    [TOKENS.COMMENT]: TOKENS.IDENTIFIER,
    [TOKENS.WHITESPACE]: TOKENS.IDENTIFIER,
    [TOKENS.EOF]: TOKENS.IDENTIFIER,
  },
  [TOKENS.NUMBER]: {
    [TOKENS.IDENTIFIER]: TOKENS.NUMBER,
    [TOKENS.NUMBER]: TOKENS.NUMBER,
    [TOKENS.STRING]: TOKENS.NUMBER,
    [TOKENS.OPERATOR]: TOKENS.NUMBER,
    [TOKENS.KEYWORD]: TOKENS.NUMBER,
    [TOKENS.PUNCTUATION]: TOKENS.NUMBER,
    [TOKENS.COMMENT]: TOKENS.NUMBER,
    [TOKENS.WHITESPACE]: TOKENS.NUMBER,
    [TOKENS.EOF]: TOKENS.NUMBER,
  },
  [TOKENS.STRING]: {
    [TOKENS.IDENTIFIER]: TOKENS.STRING,
    [TOKENS.NUMBER]: TOKENS.STRING,
    [TOKENS.STRING]: TOKENS.STRING,
    [TOKENS.OPERATOR]: TOKENS.STRING,
    [TOKENS.KEYWORD]: TOKENS.STRING,
    [TOKENS.PUNCTUATION]: TOKENS.STRING,
    [TOKENS.COMMENT]: TOKENS.STRING,
    [TOKENS.WHITESPACE]: TOKENS.STRING,
    [TOKENS.EOF]: TOKENS.STRING,
  },
  [TOKENS.OPERATOR]: {
    [TOKENS.IDENTIFIER]: TOKENS.OPERATOR,
    [TOKENS.NUMBER]: TOKENS.OPERATOR,
    [TOKENS.STRING]: TOKENS.OPERATOR,
    [TOKENS.OPERATOR]: TOKENS.OPERATOR,
    [TOKENS.KEYWORD]: TOKENS.OPERATOR,
    [TOKENS.PUNCTUATION]: TOKENS.OPERATOR,
    [TOKENS.COMMENT]: TOKENS.OPERATOR,
    [TOKENS.WHITESPACE]: TOKENS.OPERATOR,
    [TOKENS.EOF]: TOKENS.OPERATOR,
  },
  [TOKENS.KEYWORD]: {
    [TOKENS.IDENTIFIER]: TOKENS.KEYWORD,
    [TOKENS.NUMBER]: TOKENS.KEYWORD,
    [TOKENS.STRING]: TOKENS.KEYWORD,
    [TOKENS.OPERATOR]: TOKENS.KEYWORD,
    [TOKENS.KEYWORD]: TOKENS.KEYWORD,
    [TOKENS.PUNCTUATION]: TOKENS.KEYWORD,
    [TOKENS.COMMENT]: TOKENS.KEYWORD,
    [TOKENS.WHITESPACE]: TOKENS.KEYWORD,
    [TOKENS.EOF]: TOKENS.KEYWORD,
  },
  [TOKENS.PUNCTUATION]: {
    [TOKENS.IDENTIFIER]: TOKENS.PUNCTUATION,
    [TOKENS.NUMBER]: TOKENS.PUNCTUATION,
    [TOKENS.STRING]: TOKENS.PUNCTUATION,
    [TOKENS.OPERATOR]: TOKENS.PUNCTUATION,
    [TOKENS.KEYWORD]: TOKENS.PUNCTUATION,
    [TOKENS.PUNCTUATION]: TOKENS.PUNCTUATION,
    [TOKENS.COMMENT]: TOKENS.PUNCTUATION,
    [TOKENS.WHITESPACE]: TOKENS.PUNCTUATION,
    [TOKENS.EOF]: TOKENS.PUNCTUATION,
  },
  [TOKENS.COMMENT]: {
    [TOKENS.IDENTIFIER]: TOKENS.COMMENT,
    [TOKENS.NUMBER]: TOKENS.COMMENT,
    [TOKENS.STRING]: TOKENS.COMMENT,
    [TOKENS.OPERATOR]: TOKENS.COMMENT,
    [TOKENS.KEYWORD]: TOKENS.COMMENT,
    [TOKENS.PUNCTUATION]: TOKENS.COMMENT,
    [TOKENS.COMMENT]: TOKENS.COMMENT,
    [TOKENS.WHITESPACE]: TOKENS.COMMENT,
    [TOKENS.EOF]: TOKENS.COMMENT,
  },
  [TOKENS.WHITESPACE]: {
    [TOKENS.IDENTIFIER]: TOKENS.WHITESPACE,
    [TOKENS.NUMBER]: TOKENS.WHITESPACE,
    [TOKENS.STRING]: TOKENS.WHITESPACE,
    [TOKENS.OPERATOR]: TOKENS.WHITESPACE,
    [TOKENS.KEYWORD]: TOKENS.WHITESPACE,
    [TOKENS.PUNCTUATION]: TOKENS.WHITESPACE,
    [TOKENS.COMMENT]: TOKENS.WHITESPACE,
    [TOKENS.WHITESPACE]: TOKENS.WHITESPACE,
    [TOKENS.EOF]: TOKENS.WHITESPACE,
  },
  [TOKENS.EOF]: {
    [TOKENS.IDENTIFIER]: TOKENS.EOF,
    [TOKENS.NUMBER]: TOKENS.EOF,
    [TOKENS.STRING]: TOKENS.EOF,
    [TOKENS.OPERATOR]: TOKENS.EOF,
    [TOKENS.KEYWORD]: TOKENS.EOF,
    [TOKENS.PUNCTUATION]: TOKENS.EOF,
    [TOKENS.COMMENT]: TOKENS.EOF,
    [TOKENS.WHITESPACE]: TOKENS.EOF,
    [TOKENS.EOF]: TOKENS.EOF,
  },
};
