import { TOKEN_TYPE } from "./tokens";
import { DFSState } from "./dfs"; // todo: add dfsstate to the transition table itself

/**
 * Transition table for the lexer. This is a 2D table that maps the current state and the input token to the next state.
 */
type TransitionTable = Record<TOKEN_TYPE, Record<TOKEN_TYPE, TOKEN_TYPE>>;


/**
 * The actual transition table. This is a simple example and can be expanded to include more states and transitions as needed.
 */
// TODO: Refactor this transition table to a nested hashtable, from the DFS State you should get a hashtable based on the symbol, and based on that change the DFS State.
export const transitionTable: TransitionTable = {
  [TOKEN_TYPE.IDENTIFIER]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.IDENTIFIER,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.IDENTIFIER,
  },
  [TOKEN_TYPE.NUMBER]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.NUMBER,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.NUMBER,
  },
  [TOKEN_TYPE.STRING]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.STRING,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.STRING,
  },
  [TOKEN_TYPE.OPERATOR]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.OPERATOR,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.OPERATOR,
  },
  [TOKEN_TYPE.KEYWORD]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.KEYWORD,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.KEYWORD,
  },
  [TOKEN_TYPE.PUNCTUATION]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.PUNCTUATION,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.PUNCTUATION,
  },
  [TOKEN_TYPE.COMMENT]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.COMMENT,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.COMMENT,
  },
  [TOKEN_TYPE.WHITESPACE]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.WHITESPACE,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.WHITESPACE,
  },
  [TOKEN_TYPE.EOF]: {
    [TOKEN_TYPE.IDENTIFIER]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.NUMBER]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.STRING]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.OPERATOR]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.KEYWORD]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.PUNCTUATION]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.COMMENT]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.WHITESPACE]: TOKEN_TYPE.EOF,
    [TOKEN_TYPE.EOF]: TOKEN_TYPE.EOF,
  },
};
